#!/usr/bin/env python3

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = webdriver.Firefox()
for i in range(0, 10000):
    driver.get("http://localhost:8080/play.html?game=%2Fplay%2Fpython-text-adventure-game")
    element = WebDriverWait(driver, 10).until(
        EC.text_to_be_present_in_element(
            (By.ID, "game-output"),
            "Welcome to the Adventure Game"))
driver.close()
