name = "Explain Text Adventurer"
description = "A short explanation of text adventurer delivered through the medium of text adventurer."
author = "adamkewley (github)"
application = "python"
args = [ "-u", "game.py" ]
